version: "3"

services:
  frontend:
    build: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - "27017:27017"
